"""first login scnerio test 02

Revision ID: 00827df703ab
Revises: 287f3f2a4431
Create Date: 2025-06-30 05:07:51.042329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '00827df703ab'
down_revision: Union[str, None] = '287f3f2a4431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_first_login_completed', sa.Boolean(), nullable=True))
    op.drop_column('users', 'totp_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_first_login_completed')
    # ### end Alembic commands ###
