"""Modify ROutes Module Models and Add New Model Componenet

Revision ID: 158489d5fbca
Revises: 7e50a593cf37
Create Date: 2025-06-27 03:28:14.884057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '158489d5fbca'
down_revision: Union[str, None] = '7e50a593cf37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('route_module_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('removed_by', sa.Integer(), nullable=True),
    sa.Column('is_removed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['route_module_id'], ['route_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_components_id'), 'module_components', ['id'], unique=False)
    op.add_column('route_permissions', sa.Column('module_component_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'route_permissions', 'module_components', ['module_component_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'route_permissions', type_='foreignkey')
    op.drop_column('route_permissions', 'module_component_id')
    op.drop_index(op.f('ix_module_components_id'), table_name='module_components')
    op.drop_table('module_components')
    # ### end Alembic commands ###
