"""first login scnerio test

Revision ID: 287f3f2a4431
Revises: 683b40ca4a56
Create Date: 2025-06-30 04:53:50.603312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '287f3f2a4431'
down_revision: Union[str, None] = '683b40ca4a56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_enabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_two_factor_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_two_factor_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'totp_enabled')
    # ### end Alembic commands ###
