"""Modify

Revision ID: 683b40ca4a56
Revises: 158489d5fbca
Create Date: 2025-06-27 10:57:16.723153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '683b40ca4a56'
down_revision: Union[str, None] = '158489d5fbca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_component_action_uc', 'route_permissions', ['module_component_id', 'action_id'])
    op.create_unique_constraint('_module_action_uc', 'route_permissions', ['route_module_id', 'action_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_module_action_uc', 'route_permissions', type_='unique')
    op.drop_constraint('_component_action_uc', 'route_permissions', type_='unique')
    # ### end Alembic commands ###
